# Generated by Django 4.1.5 on 2023-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cust_inquiry',
        ),
    ]
