# Generated by Django 4.1.5 on 2023-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_delete_cust_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cust_inquiry',
            },
        ),
    ]
