# Generated by Django 4.1.5 on 2023-02-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cust_inquiry',
            new_name='Inquiry',
        ),
    ]
