# Generated by Django 4.1.5 on 2023-03-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
