# Generated by Django 4.1.5 on 2023-03-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_newadtype_agency'),
        ('customer', '0014_rename_user_id_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.newadtype'),
        ),
    ]
