# Generated by Django 4.1.5 on 2023-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_order_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='poster',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
