# Generated by Django 4.1.5 on 2023-03-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
    ]
