# Generated by Django 4.1.5 on 2023-03-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
