# Generated by Django 4.1.5 on 2023-03-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_newadtype_agency'),
        ('customer', '0023_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.newadtype'),
        ),
    ]
