# Generated by Django 4.1.5 on 2023-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_order_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_approve',
            name='order_date',
            field=models.DateField(),
        ),
    ]
