# Generated by Django 4.1.5 on 2023-04-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_order_word_order_approve_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
