# Generated by Django 4.1.5 on 2023-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('ownername', models.CharField(max_length=50)),
                ('established_date', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('reg_date', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agency',
            },
        ),
    ]
