# Generated by Django 4.1.5 on 2023-02-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
