# Generated by Django 4.1.5 on 2023-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0002_delete_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newadtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('pageno', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'New_AdType',
            },
        ),
    ]
