# Generated by Django 4.1.5 on 2023-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_newadtype_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newadtype',
            name='adtype',
            field=models.CharField(default='', max_length=30),
        ),
    ]
