# Generated by Django 4.1.5 on 2023-02-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_profile_user_agencyprofile'),
        ('agency', '0006_alter_newadtype_adtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newadtype',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.agencyprofile'),
        ),
    ]
